### ISSUE TITLE
Error 'NoneType' object has no attribute 'append' since upgradding to 1.1.0

### ISSUE THREAD

**Issue by lauri-openscop** [mlodic/pdfid#6]
Hello, 

I use pdfid with a django project but since I have upgraded to version 1.1.0, I got a lot of error '**NoneType' object has no attribute 'append'**

This is caused by the line 577: **disarmed_filebuffers.append(disarmed_pdf_buffer.getvalue())**
Somebody knows how to fix this ? 

Thank you

**Comment by mlodic** [comment]
so you are using the `disarm` new feature introduced, am I right? I have detected the introduced bug, I'll make a patch release
